### PR TITLE
Added Esperanto and Polish translation

### PR DESCRIPTION
**Pull request by Szafranek13**

### CODE REVIEW

**Comment by ktprograms** [comment]
Hi, could you please add `fastlane/metadata/android/eo/full_description.txt` and `fastlane/metadata/android/eo/short_description.txt`? You can refer to #10 for more information. Thanks!

**Comment by Szafranek13** [comment]
I'll be honest, I'm too lazy to make long_description.txt for Esperanto. Sorry

**Comment by ktprograms** [comment]
Thanks anyway for what you did!

**Comment by ktprograms** [comment]
BTW it seems Android doesn't have Esperanto as a language?

**Comment by Szafranek13** [comment]
You can use for example [Language Changer](https://play.google.com/store/apps/details?id=com.dogfeederz.localechanger) just like I and many esperantists did. It lists every UTF-8 locale and let you change Android lang to it.

**Pull request merged**
