### PR TITLE
Translation of short_description.txt, full_description.txt, and strings.xml in French.

### PR DESCRIPTION
**Pull request by Sitavi**

### CODE REVIEW

**Comment by ktprograms** [comment]
Hi, thanks for the translation!

I've moved the menu strings (band colour selection dropdown menu) into `values/strings.xml`. Would you mind also translating the menu strings to French?

The current project structure (only the `values/strings.xml` part) is:

```
|- app
   |- src
      |- main
         |- res
            |- values
               |- strings.xml
```

If you are okay to translate, please make a `values-fr` folder in the `res` folder, then put a `strings.xml` file in that folder with the French translated strings. The project structure (only the `values/strings.xml` part) would then be:

```
|- app
   |- src
      |- main
         |- res
            |- values
               |- strings.xml
            |- values-fr
               |- strings.xml
```

**Comment by Sitavi** [comment]
I did it

**Comment by ktprograms** [comment]
I renamed the `\` to a `/` in the filename. I think this is ready to merge. Thanks!

**Comment by Sitavi** [comment]
Little mistake :)
Your're welcome ! 
PS : Just for record, I can't use 6 band mode in f-droid alpha v0.1.3 
normal ?

**Comment by ktprograms** [comment]
I only added 6 band mode in a later version (not yet on F-Droid).

**Pull request merged**
